name = "test"
hosts = ["constantinides", "localhost"]
workdir = "./workdir"
executable = "test.sh"
repeat = 2
threads_per_task = 1

[arguments]
hash_size = ["64", "32"]
percentage_of_duplicates = ["0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9"]
